
Vagrant.configure("2") do |config|

  config.vm.box = "CentOS-6.3-x86_64-minimal"

  config.vm.network :private_network, ip: "192.168.50.20"

  config.vm.provision :shell, :path => "bootstrap.sh", :args => "192.168.50.20"

end

