
Vagrant.configure("2") do |config|
  config.vm.box = "CentOS-6.3-x86_64-minimal"
  config.vm.box_url = "https://dl.dropbox.com/u/7225008/Vagrant/CentOS-6.3-x86_64-minimal.box"

  PROJECT="examples"
  RUNDECK_YUM_REPO="https://bintray.com/rundeck/rundeck-rpm/rpm"

  RERUN_YUM_REPO="https://bintray.com/rerun/rerun-rpm/rpm"
  PRIMARY="rundeck1"
  SECONDARY="rundeck2"
  WEBDAV_URL="http://192.168.50.7/dav"

  config.vm.define :mysql do |mysql|
    mysql.vm.hostname = "centos-mysql.local"
    mysql.vm.network :private_network, ip: "192.168.50.6"
    mysql.vm.provision :shell, :path => "install-mysql.sh", :args => "'mysql'"
  end


  config.vm.define :webdav do |webdav|
    webdav.vm.hostname = "centos-webdav.local"
    webdav.vm.network :private_network, ip: "192.168.50.7"
    webdav.vm.provision :shell, :path => "install-httpd.sh", :args => "'webdav'"
  end

  config.vm.define :rundeck1 do |primary|
    primary.vm.hostname = "#{PRIMARY}"
    primary.vm.network :private_network, ip: "192.168.50.14"
    primary.vm.provision :shell, :path => "install-rundeck.sh", :args => "#{PRIMARY} 192.168.50.6 #{RUNDECK_YUM_REPO} #{RERUN_YUM_REPO} #{WEBDAV_URL}"
    primary.vm.provision :shell, :path => "add-project.sh", :args => "#{PROJECT} #{PRIMARY} 192.168.50.14 rundeck,primary #{WEBDAV_URL}"
    primary.vm.provision :shell, :path => "generate-apikey.sh"
  end

  config.vm.define :rundeck2 do |secondary|
    secondary.vm.hostname = "#{SECONDARY}"
    secondary.vm.network :private_network, ip: "192.168.50.15"
    secondary.vm.provision :shell, :path => "install-rundeck.sh", :args => "#{SECONDARY} 192.168.50.6 #{RUNDECK_YUM_REPO} #{RERUN_YUM_REPO} #{WEBDAV_URL}"
    secondary.vm.provision :shell, :path => "add-project.sh", :args => "#{PROJECT} #{SECONDARY} 192.168.50.15 rundeck,secondary #{WEBDAV_URL}"
    secondary.vm.provision :shell, :path => "add-primary.sh", :args => "#{PROJECT} #{PRIMARY} 192.168.50.14"
    secondary.vm.provision :shell, :path => "load-jobs.sh", :args => "#{PROJECT} 192.168.50.14:4440"
  end

end

