
Vagrant.configure("2") do |config|

  config.vm.box = "precise32"

  config.vm.network :forwarded_port, guest: 4440, host: 14440

  deb_repo_url="http://dl.bintray.com/rundeck/rundeck-deb"

  config.vm.provision :shell, :path => "install-rundeck.sh", :args => deb_repo_url
  config.vm.provision :shell, :path => "add-project.sh"

end
