
Vagrant.configure("2") do |config|
  config.vm.box = "CentOS-6.3-x86_64-minimal"
  config.vm.box_url = "https://dl.dropbox.com/u/7225008/Vagrant/CentOS-6.3-x86_64-minimal.box"

  PROJECT="examples"


  config.vm.define :mysql do |mysql|
    mysql.vm.hostname = "mysql"
    mysql.vm.network :private_network, ip: "192.168.50.6"
    mysql.vm.provision :shell, :path => "install-mysql.sh", :args => "mysql"
  end

  config.vm.define :rundeck do |rundeck|
    rundeck.vm.hostname = "rundeck"
    rundeck.vm.network :private_network, ip: "192.168.50.4"
    rundeck.vm.provision :shell, :path => "install-rundeck.sh", :args => "1.6.2 rundeck 192.168.50.4 192.168.50.6"
    rundeck.vm.provision :shell, :path => "add-project.sh", :args => "#{PROJECT} rundeck 192.168.50.4 rundeck,rundeck"
  end


end

