
Vagrant.configure("2") do |config|
  config.vm.box = "CentOS-6.3-x86_64-minimal"
  config.vm.box_url = "https://dl.dropbox.com/u/7225008/Vagrant/CentOS-6.3-x86_64-minimal.box"

  PROJECT="examples"
  RUNDECK_VERSION="2.0.0"
  RUNDECK_IP="192.168.50.14"
  MYSQL_IP="192.168.50.16"

  config.vm.define :mysql do |mysql|
    mysql.vm.hostname = "mysql"
    mysql.vm.network :private_network, ip: "#{MYSQL_IP}"
    mysql.vm.provision :shell, :path => "install-mysql.sh", :args => "mysql"
  end

  config.vm.define :rundeck do |rundeck|
    rundeck.vm.hostname = "rundeck"
    rundeck.vm.network :private_network, ip: "#{RUNDECK_IP}"
    rundeck.vm.provision :shell, :path => "install-rundeck.sh", :args => "#{RUNDECK_VERSION} rundeck #{RUNDECK_IP} #{MYSQL_IP}"
    rundeck.vm.provision :shell, :path => "add-project.sh", :args => "#{PROJECT} rundeck #{RUNDECK_IP} rundeck,rundeck"
  end


end

