
Vagrant.configure("2") do |config|

  #RUNDECK_YUM_REPO="https://bintray.com/rundeck/candidate-rpm/rpm"
  RUNDECK_YUM_REPO="https://bintray.com/gschueler/ci-rundeck2-rpm/rpm"
  RUNDECK_IP="192.168.50.4"
  NAME="rundeck"

  config.vm.box = "CentOS-6.3-x86_64-minimal"
  config.vm.box_url = "https://dl.dropbox.com/u/7225008/Vagrant/CentOS-6.3-x86_64-minimal.box"

  config.vm.network :forwarded_port, guest: 4440, host: 14440
  config.vm.network :forwarded_port, guest: 389, host: 3890

  config.vm.network :private_network, ip: "#{RUNDECK_IP}"

  config.vm.provision :shell, :path => "provisioning/install-openldap.sh"
  config.vm.provision :shell, :path => "provisioning/install-rundeck.sh", :args => "#{NAME} #{RUNDECK_IP} #{RUNDECK_YUM_REPO}"

end
