
Vagrant.configure("2") do |config|
  config.vm.box = "CentOS-6.3-x86_64-minimal"
  config.vm.box_url = "https://dl.dropbox.com/u/7225008/Vagrant/CentOS-6.3-x86_64-minimal.box"

  IP="192.168.50.20"

  config.vm.define :nexus do |nexus|
    nexus.vm.hostname = "nexus"
    nexus.vm.network :private_network, ip: "#{IP}"
    nexus.vm.provision :shell, :path => "provisioning/install-nexus.sh", :args => "#{IP}"
  end

end

