
Vagrant.configure("2") do |config|

  config.vm.box = "dummy"

  config.vm.network :forwarded_port, guest: 4440, host: 14440

  config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.provision :shell, :path => "add-project.sh"

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = "AKIAJEGKRJGKJOCT4FLQ"
    aws.secret_access_key = "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"
    aws.keypair_name = "aws-vagrant-test"

    aws.security_groups = "vagrant-test"

    aws.ami = "ami-7747d01e"


    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "/Users/alexh/Development/rundeck-workspace/rundeck-vagrant/aws/aws-vagrant-test.pem"
  end
end
