
Vagrant.configure("2") do |config|
  config.vm.box = "CentOS-6.3-x86_64-minimal"
  config.vm.box_url = "https://dl.dropbox.com/u/7225008/Vagrant/CentOS-6.3-x86_64-minimal.box"

  IP="192.168.50.10"
  RUNDECK_IP="192.168.50.4"

  config.vm.define :jenkins do |jenkins|
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.network :private_network, ip: "#{IP}"
    jenkins.vm.provision :shell, :path => "provisioning/install-jenkins.sh", :args => "#{RUNDECK_IP}"
  end

end

